version: '3.8'
services:
 jenkins:
   image: jenkins/jenkins:lts
   privileged: true
   user: root
   ports:
      - 8081:8080
      - 50000:50000
   container_name: myjenkins-server
   restart: always

   volumes:
      - /root/project-devops/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock