---
- hosts: ansible
  tasks: 
  - name: create docker image
    command: docker build -t regestryapp:latest .
    args:
      chdir: /opt/monapp
  - name: create tag to push onto dockerhub
    command: docker tag regestryapp:latest sabrinasabrina/monappli:latest

  - name: push docker image onto dockerhub
    command: docker push sabrinasabrina/monappli:latest