apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapphub-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapphub
  template:
    metadata:
      labels:
        app: myapphub
    spec:
      containers:
      - name: myapphub-container
        image: sabrinasabrina/myregappvpip:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub-credentials